In [1]:
import pandas as pd
import numpy as np

In [3]:
csv=pd.read_csv("test.csv")
csv

id  rho  650_src  660_src  670_src  680_src  690_src  700_src  \
0     10000   15  0.15406  0.23275  0.30977  0.42949  0.51264  0.62558   
1     10001   15  0.48552  0.56939  0.67575  0.79089  0.85114  0.92581   
2     10002   10  0.46883  0.56085  0.62442  0.73172  0.81724  0.91517   
3     10003   10  0.06905  0.07517  0.10226  0.14905  0.16182  0.19659   
4     10004   25  0.00253  0.00757  0.01649  0.00128  0.00000  0.00000   
...     ...  ...      ...      ...      ...      ...      ...      ...   
9995  19995   15  0.04334  0.03279  0.05853  0.04070  0.07704  0.07859   
9996  19996   25  0.00020  0.02009  0.01726  0.03816  0.08300  0.08681   
9997  19997   15  0.00000  0.00000  0.00120  0.00000  0.04347  0.14882   
9998  19998   20  0.08390  0.05690  0.08343  0.12324  0.12720  0.16732   
9999  19999   15  0.11016  0.11505  0.13086  0.12352  0.14200  0.15434   

      710_src  720_src  ...       900_dst       910_dst       920_dst  \
0     0.74340  0.85418  ...  0.000000e+00  0.000000e+00  1.432248e-14   
1     0.98071  0.98177  ...  1.036013e-13           NaN  2.830975e-14   
2     0.94801  0.99108  ...           NaN           NaN           NaN   
3     0.26085  0.36753  ...  1.651177e-11  7.282747e-12  5.010879e-12   
4     0.00105  0.01975  ...  0.000000e+00  0.000000e+00  0.000000e+00   
...       ...      ...  ...           ...           ...           ...   
9995  0.06168  0.08903  ...  7.889599e-13           NaN  4.903209e-13   
9996  0.15300  0.18099  ...  1.240848e-17  6.258180e-18  8.693704e-20   
9997  0.40883  0.80365  ...  0.000000e+00           NaN  0.000000e+00   
9998  0.18149  0.23766  ...  0.000000e+00  7.084232e-18           NaN   
9999  0.18970  0.19676  ...  7.524188e-13  3.672244e-13  4.847909e-13   

           930_dst       940_dst       950_dst       960_dst       970_dst  \
0     0.000000e+00  0.000000e+00  6.332117e-15  1.429966e-14  0.000000e+00   
1     1.114337e-13  4.825731e-14           NaN  2.282485e-14  7.348414e-14   
2              NaN  1.569208e-11  6.242378e-12           NaN  1.219010e-11   
3              NaN  1.571023e-11  0.000000e+00  0.000000e+00  3.304247e-12   
4     0.000000e+00  3.732057e-17  4.110605e-17  0.000000e+00  0.000000e+00   
...            ...           ...           ...           ...           ...   
9995  1.365078e-12  7.929664e-13  0.000000e+00  0.000000e+00  1.472213e-13   
9996           NaN  4.514449e-18           NaN  9.128300e-19           NaN   
9997  2.610282e-14  7.789652e-15           NaN  1.271388e-15  1.436617e-15   
9998  0.000000e+00  2.669004e-18  8.586549e-18  0.000000e+00  4.489194e-18   
9999  3.944395e-13  3.177592e-13  3.678863e-15  1.223018e-13  1.152641e-13   

           980_dst       990_dst  
0              NaN  7.320236e-14  
1     1.259055e-13  2.349874e-13  
2              NaN           NaN  
3     4.106134e-11           NaN  
4     1.910775e-16  2.215673e-15  
...            ...           ...  
9995  1.479745e-12  5.391520e-12  
9996  3.928314e-18  2.586781e-17  
9997  0.000000e+00  1.743751e-13  
9998  2.892986e-17           NaN  
9999  5.594120e-13  1.763446e-12  

[10000 rows x 72 columns]

In [16]:
size=len(csv)
x_col=csv.columns[1:]
isNan=csv.isna()


x=csv[[i for i in x_col]].as_matrix()
x=[]
for i in range(size):
    temp=[]
    for col in x_col:
        #결측치면 평균으로
        if isNan[col][i]:
            temp.append(csv.mean()[col])
        else:
            temp.append(csv[col][i])
    x.append(temp)
x=np.array(x,dtype=np.float64)


C:\anaconda\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [1]:
#모델 불러오기
from tensorflow.python.keras.models import load_model


model=load_model("1.softmax_model.h5")

In [18]:
y=model.predict_proba(x)

In [19]:
print(y)

[[0.33037364 0.16974759 0.37687385 0.12300503]
 [0.32971713 0.16985272 0.3774085  0.12302165]
 [0.3209559  0.17038941 0.38397127 0.12468349]
 ...
 [0.32083488 0.17013516 0.3793988  0.1296312 ]
 [0.3275651  0.17535041 0.37093887 0.12614563]
 [0.321753   0.17105325 0.38156965 0.12562409]]
